---
services: docker

addons:
  hosts:
    - cluster.pidramble.test
    - registry.pidramble.test
    - kube1

install:
  - docker pull geerlingguy/docker-debian10-ansible:latest
  - cp example.config.yml config.yml

script:
  # - "travis_wait 30 ./testing/docker/docker-playbook-test.sh"
  - ./testing/docker/docker-playbook-test.sh

after_failure:
  - docker exec --tty dramble env TERM=xterm journalctl --no-pager -u kubelet
